CREATE DATABASE EMPLOYEE;

CREATE TABLE EMP(
	ID INT,
	NAME VARCHAR(50)
);

INSERT INTO EMP (ID, NAME) VALUES (1, 'JAMES');
INSERT INTO EMP (ID, NAME) VALUES (2, 'YUKI');

DELETE FROM EMP;

SELECT * FROM EMP;